language: php

sudo: false

php:
  - 7.0
  - 7.1

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then phpenv config-rm xdebug.ini; fi
  - composer install --prefer-dist --no-interaction

script:
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]]; then vendor/bin/phpunit; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then vendor/bin/phpunit --coverage-clover clover.xml; fi
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then vendor/bin/phpcs -n -p --extensions=php --standard=PSR2 ./src ./tests; fi

after_success:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
